<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionObject.proto

namespace App\Models\Buffer\Entity\GPBMetadata;

class SessionObject
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a1353657373696f6e4f626a6563742e70726f746f12186170702e6d" .
            "6f64656c732e6275666665722e656e7469747922190a0a53657373696f6e" .
            "4f626a120b0a037569641801200128034227e202244170702f4d6f64656c" .
            "732f4275666665722f456e746974792f4750424d65746164617461620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

