<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionObject.proto

namespace App\Models\Buffer\Entity\GPBMetadata;

class SessionObject
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89010a1353657373696f6e4f626a6563742e70726f746f12186170702e" .
            "6d6f64656c732e6275666665722e656e7469747922270a0a53657373696f" .
            "6e4f626a120b0a03756964180120012803120c0a046e69636b1802200128" .
            "094227e202244170702f4d6f64656c732f4275666665722f456e74697479" .
            "2f4750424d65746164617461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

